config/routes.rb
PdfUploader::Application.routes.draw do
  resources :uploads

resources :uploads, :only => [:index, :destroy, :show, :create, :new]
root :to => "uploads#index"

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :uploaded 
  has_attached_file :uploaded, :styles => { :thumb => "100x100>" }
#  validates_attachment_content_type :uploaded, :content_type => "pdf"
#  validates_attachment_presence :uploaded
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = Upload.all
  end

  def show
    @upload = Upload.find(params[:id])
  end
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @upload }
    end
  end
  
  def create
      @upload = Upload.new(params[:upload])
      if @upload.save!
        flash[:notice] = "Successfully created upload."
        respond_to do |format|
          format.html {redirect_to uploads_path}
        end
      else
        render :action => 'new'
      end
    end
    def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy
    flash[:notice] = "Successfully destroyed upload."
    redirect_to uploads_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js", "jquery.rails.js", "application.js" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/uploads/_index.html.erb
<%= javascript_include_tag "swfobject.js", "jquery.uploadify.v2.1.0.js" %>
<script type="text/javascript" charset="utf-8">
<%- session_key = Rails.application.config.session_options[:key] -%> 
$(document).ready(function() {
	
	$('#upload_photo').click(function(event){ 
		event.preventDefault();
	}); 
	
	$('#upload_photo').uploadify({
  	uploader : '/uploadify/uploadify.swf',
		cancelImg : '/uploadify/cancel.png',
		multi : true,
		auto : true,
  	script : '/uploads',
		onComplete : function(event, queueID, fileObj, response, data) { 
			var dat = eval('(' + response + ')');
			$.getScript(dat.upload);},
  	scriptData : {
	        '_http_accept': 'application/javascript',
					'format' : 'json',
	        '_method': 'post'
	      }
	});
	
	$('#upload_submit').click(function(event){ 
			event.preventDefault(); 
			$('#upload_photo').uploadifyUpload(); 
		});
		
}); 
</script>

app/views/uploads/index.html.erb
<% title "Uploads" %>
<%= render :partial => "index" %>

<h3>Upload a Photo</h3> 
<%= form_for Upload.new, :html => {:multipart => true} do |f| %> 
<p><%= f.file_field :photo %> </p>
<% end %>

app/views/uploads/show.html.erb
<% title "Upload" %>

<p>
  <strong>Name:</strong>
  <%= @upload.name %>
</p>

<p>
  <%= link_to "Edit", edit_upload_path(@upload) %> |
  <%= link_to "Destroy", @upload, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", uploads_path %>
</p>